version: '3.8'

services:
  database:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: talkwith
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb-data: